services:
  app:
    build: .
    image: "${IMAGE:-psychotherapie-seliger:dev}"
    command: ["npm", "run", "test"]
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
