name: Run pipeline
on:
  pull_request:

permissions:
  contents: "read"
  id-token: "write"

jobs:
  test:
    uses: PeterLaudel/actions/.github/workflows/pipeline.yml@main
    secrets: inherit
    with:
      e2e: true
  
  