name: Run pipeline
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    uses: PeterLaudel/actions/.github/workflows/pipeline.yml@main
    secrets: inherit
    permissions:
      contents: write
      id-token: write
    with:
      e2e: true
  
  